version: '3.9'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'postgres_db'
    environment:
      POSTGRES_USER: pastebox
      POSTGRES_PASSWORD: pastebox
      POSTGRES_DB: pastebox_db

  app:
    build:
      context: .
    container_name: 'app_container'
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/pastebox_db